import cv2 as cv

lena = cv.imread('../lena.jpg', 0)
r1, d1 = cv.threshold(lena, 127, 255, cv.THRESH_BINARY)
r2, d2 = cv.threshold(lena, 127, 255, cv.THRESH_BINARY_INV)
r3, d3 = cv.threshold(lena, 127, 255, cv.THRESH_TRUNC)
r4, d4 = cv.threshold(lena, 127, 255, cv.THRESH_TOZERO_INV)
r5, d5 = cv.threshold(lena, 127, 255, cv.THRESH_TOZERO)
d6 = cv.adaptiveThreshold(lena,255,cv.ADAPTIVE_THRESH_MEAN_C,cv.THRESH_BINARY,5,3)
d7 = cv.adaptiveThreshold(lena,255,cv.ADAPTIVE_THRESH_GAUSSIAN_C,cv.THRESH_BINARY,5,3)
r8,d8 = cv.threshold(lena,0,255,cv.THRESH_BINARY + cv.THRESH_OTSU)
cv.imshow('lena', lena)
print(r1)
print(r2)
print(r3)
print(r4)
print(r5)
print(r8)
cv.imshow('d1', d1)
cv.imshow('d2', d2)
cv.imshow('d3', d3)
cv.imshow('d4', d4)
cv.imshow('d5',d5)
cv.imshow('d6',d6)
cv.imshow('d7',d7)
cv.imshow('d8',d8)
cv.waitKey()
cv.destroyAllWindows()
